package render

import (
	"bufio"
	"encoding/json"
	"fmt"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"text/template"

	"github.com/oleksandrskoruk/docusnap/internal/model"
)

var templateSources = map[string]string{
	"README.generated.md": `# Project Documentation

Generated by DocuSnap.

## Overview
- Path: {{ .ProjectPath }}
- Scanned at: {{ .ScannedAt }}

## Languages
{{- if .Languages }}
{{- range .Languages }}
- {{ . }}
{{- end }}
{{- else }}
- n/a
{{- end }}

## Frameworks
{{- if .Frameworks }}
{{- range .Frameworks }}
- {{ . }}
{{- end }}
{{- else }}
- n/a
{{- end }}

## Artifacts
- [Dependencies](dependencies.md)
- [Dependency Graph](dependency-graph.md)
- [Module Graph](module-graph.md)
- [Endpoints](endpoints.md)
- [Architecture](architecture.md)
`,
	"dependencies.md": `# Dependencies

{{- if .DependencyManagers }}
{{- range .DependencyManagers }}
## {{ . }}
{{- $deps := index $.Dependencies . }}
{{- if $deps }}
| Name | Version |
|---|---|
{{- range $deps }}
| {{ .Name }} | {{ .Version }} |
{{- end }}
{{- else }}
No dependencies detected.
{{- end }}

{{- end }}
{{- else }}
No dependencies detected.
{{- end }}
`,
	"endpoints.md": `# API Endpoints

{{- if .Routes }}
| Method | Path | Controller |
|---|---|---|
{{- range .Routes }}
| {{ .Method }} | {{ .Path }} | {{ .Controller }} |
{{- end }}
{{- else }}
No endpoints detected for the current project.
{{- end }}
`,
	"dependency-graph.md": `# Dependency Graph

{{- if .DependencyGraphMermaid }}
{{ .DependencyGraphMermaid }}
{{- else }}
No dependencies detected.
{{- end }}
`,
	"module-graph.md": `# Module Graph

Overview graph collapsed by module path for readability.

{{- if .ModuleGraphMermaid }}
{{ .ModuleGraphMermaid }}
{{- else }}
No module links detected.
{{- end }}
`,
	"architecture.md": `# Architecture

## Layer Diagram

~~~mermaid
graph TD
Controllers --> Services
Services --> Repositories
Repositories --> Database
~~~

## Technology View
{{- if .Frameworks }}
{{- range .Frameworks }}
- Framework: {{ . }}
{{- end }}
{{- else }}
- Framework: n/a
{{- end }}
{{- if .Infrastructure }}
{{- range .Infrastructure }}
- Infrastructure: {{ . }}
{{- end }}
{{- else }}
- Infrastructure: n/a
{{- end }}
`,
}

var templateNameByOutput = map[string]string{
	"README.generated.md": "readme.md.tmpl",
	"dependencies.md":     "dependencies.md.tmpl",
	"endpoints.md":        "endpoints.md.tmpl",
	"dependency-graph.md": "dependency-graph.md.tmpl",
	"module-graph.md":     "module-graph.md.tmpl",
	"architecture.md":     "architecture.md.tmpl",
}

type templateData struct {
	model.Snapshot
	DependencyManagers     []string
	DependencyGraphMermaid string
	ModuleGraphMermaid     string
}

// Generate writes the markdown documentation set to outDir.
func Generate(snap model.Snapshot, outDir string) ([]string, error) {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return nil, err
	}

	managers := make([]string, 0, len(snap.Dependencies))
	for manager := range snap.Dependencies {
		managers = append(managers, manager)
	}
	sort.Strings(managers)

	data := templateData{
		Snapshot:               snap,
		DependencyManagers:     managers,
		DependencyGraphMermaid: buildDependencyGraphMermaid(snap.Dependencies),
		ModuleGraphMermaid:     buildModuleGraphMermaid(snap.ProjectPath),
	}

	generated := make([]string, 0, len(templateSources))
	templateDir := filepath.Join(snap.ProjectPath, "templates")
	for name, src := range templateSources {
		path := filepath.Join(outDir, name)
		templateBody, err := resolveTemplateSource(templateDir, name, src)
		if err != nil {
			return nil, err
		}
		if err := renderFile(path, templateBody, data); err != nil {
			return nil, fmt.Errorf("render %s: %w", name, err)
		}
		generated = append(generated, path)
	}

	sort.Strings(generated)
	return generated, nil
}

func renderFile(path, src string, data templateData) error {
	tmpl, err := template.New(filepath.Base(path)).Parse(src)
	if err != nil {
		return err
	}

	var b strings.Builder
	if err := tmpl.Execute(&b, data); err != nil {
		return err
	}

	return os.WriteFile(path, []byte(strings.TrimSpace(b.String())+"\n"), 0o644)
}

func resolveTemplateSource(templateDir, outName, fallback string) (string, error) {
	templateName, ok := templateNameByOutput[outName]
	if !ok {
		return fallback, nil
	}

	customPath := filepath.Join(templateDir, templateName)
	data, err := os.ReadFile(customPath)
	if err != nil {
		if os.IsNotExist(err) {
			return fallback, nil
		}
		return "", fmt.Errorf("read template %s: %w", customPath, err)
	}

	body := strings.TrimSpace(string(data))
	if body == "" {
		return fallback, nil
	}

	return body, nil
}

func buildDependencyGraphMermaid(deps map[string][]model.Dependency) string {
	if len(deps) == 0 {
		return ""
	}

	managers := make([]string, 0, len(deps))
	for manager := range deps {
		managers = append(managers, manager)
	}
	sort.Strings(managers)

	var b strings.Builder
	b.WriteString("~~~mermaid\n")
	b.WriteString("graph LR\n")
	b.WriteString(`  P["Project"]` + "\n")

	for i, manager := range managers {
		managerID := fmt.Sprintf("PM%d", i+1)
		b.WriteString(fmt.Sprintf(`  %s["%s"]`+"\n", managerID, escapeMermaidLabel(manager)))
		b.WriteString(fmt.Sprintf("  P --> %s\n", managerID))

		for j, dep := range deps[manager] {
			depID := fmt.Sprintf("D%d_%d", i+1, j+1)
			b.WriteString(fmt.Sprintf(`  %s["%s"]`+"\n", depID, escapeMermaidLabel(dep.Name)))
			b.WriteString(fmt.Sprintf("  %s --> %s\n", managerID, depID))
		}
	}

	b.WriteString("~~~")
	return b.String()
}

func escapeMermaidLabel(v string) string {
	return strings.ReplaceAll(v, `"`, `'`)
}

type moduleEdge struct {
	From string
	To   string
}

type phpAutoloadMapping struct {
	Prefix string
	Dir    string
}

func buildModuleGraphMermaid(root string) string {
	edges := collectModuleOverviewEdges(root)
	if len(edges) == 0 {
		return ""
	}

	nodeID := map[string]string{}
	nodes := make([]string, 0)
	groups := map[string][]string{}
	nextID := 1
	for _, edge := range edges {
		if _, ok := nodeID[edge.From]; !ok {
			nodeID[edge.From] = fmt.Sprintf("M%d", nextID)
			nextID++
			nodes = append(nodes, edge.From)
			group := moduleGroup(edge.From)
			groups[group] = append(groups[group], edge.From)
		}
		if _, ok := nodeID[edge.To]; !ok {
			nodeID[edge.To] = fmt.Sprintf("M%d", nextID)
			nextID++
			nodes = append(nodes, edge.To)
			group := moduleGroup(edge.To)
			groups[group] = append(groups[group], edge.To)
		}
	}

	sort.Strings(nodes)
	groupNames := make([]string, 0, len(groups))
	for group := range groups {
		groupNames = append(groupNames, group)
		sort.Strings(groups[group])
	}
	sort.Strings(groupNames)

	var b strings.Builder
	b.WriteString("~~~mermaid\n")
	b.WriteString("graph TD\n")
	for _, group := range groupNames {
		groupID := sanitizeMermaidID("G_" + group)
		b.WriteString(fmt.Sprintf(`  subgraph %s["%s"]`+"\n", groupID, escapeMermaidLabel(group)))
		for _, label := range groups[group] {
			b.WriteString(fmt.Sprintf(`    %s["%s"]`+"\n", nodeID[label], escapeMermaidLabel(label)))
		}
		b.WriteString("  end\n")
	}
	for _, edge := range edges {
		b.WriteString(fmt.Sprintf("  %s --> %s\n", nodeID[edge.From], nodeID[edge.To]))
	}
	b.WriteString("~~~")
	return b.String()
}

func collectModuleImportEdges(root string) []moduleEdge {
	rootAbs, err := filepath.Abs(root)
	if err != nil {
		return nil
	}

	modulePath := parseGoModulePath(rootAbs)
	phpMappings := parsePHPAutoloadMappings(rootAbs)
	set := map[string]struct{}{}
	out := make([]moduleEdge, 0)

	_ = filepath.WalkDir(rootAbs, func(path string, d os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return nil
		}
		if d.IsDir() {
			base := d.Name()
			if base == ".git" || base == "node_modules" || base == "vendor" || base == "__tests__" || strings.HasPrefix(base, ".") {
				if path != rootAbs {
					return filepath.SkipDir
				}
			}
			return nil
		}

		if isTestModuleFile(path) {
			return nil
		}

		ext := strings.ToLower(filepath.Ext(path))
		var edges []moduleEdge
		switch ext {
		case ".go":
			edges = parseGoImportEdges(rootAbs, path, modulePath)
		case ".js", ".mjs", ".cjs", ".ts":
			edges = parseJSImportEdges(rootAbs, path)
		case ".py":
			edges = parsePythonImportEdges(rootAbs, path)
		case ".php":
			edges = parsePHPImportEdges(rootAbs, path, phpMappings)
		default:
			return nil
		}

		for _, edge := range edges {
			if edge.From == "" || edge.To == "" || edge.From == edge.To {
				continue
			}
			key := edge.From + "->" + edge.To
			if _, ok := set[key]; ok {
				continue
			}
			set[key] = struct{}{}
			out = append(out, edge)
		}
		return nil
	})

	sort.Slice(out, func(i, j int) bool {
		if out[i].From == out[j].From {
			return out[i].To < out[j].To
		}
		return out[i].From < out[j].From
	})

	const maxEdges = 300
	if len(out) > maxEdges {
		return out[:maxEdges]
	}
	return out
}

func collectModuleOverviewEdges(root string) []moduleEdge {
	raw := collectModuleImportEdges(root)
	if len(raw) == 0 {
		return nil
	}

	weights := map[string]int{}
	byKey := map[string]moduleEdge{}
	for _, edge := range raw {
		from := normalizeModuleOverviewNode(edge.From)
		to := normalizeModuleOverviewNode(edge.To)
		if from == "" || to == "" || from == to {
			continue
		}
		key := from + "->" + to
		weights[key]++
		byKey[key] = moduleEdge{From: from, To: to}
	}

	type weightedEdge struct {
		moduleEdge
		weight int
	}

	weighted := make([]weightedEdge, 0, len(byKey))
	for key, edge := range byKey {
		weighted = append(weighted, weightedEdge{
			moduleEdge: edge,
			weight:     weights[key],
		})
	}

	sort.Slice(weighted, func(i, j int) bool {
		if weighted[i].weight == weighted[j].weight {
			if weighted[i].From == weighted[j].From {
				return weighted[i].To < weighted[j].To
			}
			return weighted[i].From < weighted[j].From
		}
		return weighted[i].weight > weighted[j].weight
	})

	const maxOverviewEdges = 120
	if len(weighted) > maxOverviewEdges {
		weighted = weighted[:maxOverviewEdges]
	}

	out := make([]moduleEdge, 0, len(weighted))
	for _, edge := range weighted {
		out = append(out, edge.moduleEdge)
	}
	return out
}

func isTestModuleFile(path string) bool {
	base := strings.ToLower(filepath.Base(path))
	switch {
	case strings.HasSuffix(base, "_test.go"):
		return true
	case strings.HasSuffix(base, ".test.js"),
		strings.HasSuffix(base, ".spec.js"),
		strings.HasSuffix(base, ".test.mjs"),
		strings.HasSuffix(base, ".spec.mjs"),
		strings.HasSuffix(base, ".test.cjs"),
		strings.HasSuffix(base, ".spec.cjs"),
		strings.HasSuffix(base, ".test.ts"),
		strings.HasSuffix(base, ".spec.ts"):
		return true
	case strings.HasPrefix(base, "test_") && strings.HasSuffix(base, ".py"):
		return true
	case strings.HasSuffix(base, "_test.py"):
		return true
	case strings.HasSuffix(base, "test.php"):
		return true
	case strings.Contains(filepath.ToSlash(path), "/tests/"):
		return true
	default:
		return false
	}
}

func normalizeModuleOverviewNode(path string) string {
	path = filepath.ToSlash(strings.TrimSpace(path))
	path = strings.TrimPrefix(path, "./")
	path = strings.Trim(path, "/")
	if path == "" || path == "." {
		return "root"
	}

	base := strings.TrimSuffix(filepath.Base(path), filepath.Ext(path))
	dir := filepath.ToSlash(filepath.Dir(path))
	switch base {
	case "index", "main", "mod", "__init__":
		if dir == "." || dir == "" {
			return "root"
		}
		path = dir
	default:
		path = strings.TrimSuffix(path, filepath.Ext(path))
	}

	parts := strings.Split(path, "/")
	filtered := make([]string, 0, len(parts))
	for _, part := range parts {
		if part == "" || part == "." {
			continue
		}
		filtered = append(filtered, part)
	}
	if len(filtered) == 0 {
		return "root"
	}
	if len(filtered) == 1 {
		return filtered[0]
	}
	if len(filtered) > 2 {
		filtered = filtered[:2]
	}
	return strings.Join(filtered, "/")
}

func moduleGroup(label string) string {
	parts := strings.Split(label, "/")
	if len(parts) == 0 || parts[0] == "" {
		return "root"
	}
	return parts[0]
}

func sanitizeMermaidID(v string) string {
	var b strings.Builder
	for _, r := range v {
		switch {
		case r >= 'a' && r <= 'z':
			b.WriteRune(r)
		case r >= 'A' && r <= 'Z':
			b.WriteRune(r)
		case r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	if b.Len() == 0 {
		return "G_root"
	}
	return b.String()
}

func parseGoModulePath(root string) string {
	goModPath := filepath.Join(root, "go.mod")
	file, err := os.Open(goModPath)
	if err != nil {
		return ""
	}
	defer file.Close()

	s := bufio.NewScanner(file)
	for s.Scan() {
		line := strings.TrimSpace(s.Text())
		if strings.HasPrefix(line, "module ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "module "))
		}
	}
	return ""
}

func parseGoImportEdges(root, path, modulePath string) []moduleEdge {
	fileSet := token.NewFileSet()
	f, err := parser.ParseFile(fileSet, path, nil, parser.ImportsOnly)
	if err != nil {
		return nil
	}

	from := toProjectRelative(root, path)
	edges := make([]moduleEdge, 0, len(f.Imports))
	for _, imp := range f.Imports {
		importPath := strings.Trim(imp.Path.Value, `"`)
		if modulePath == "" || !strings.HasPrefix(importPath, modulePath) {
			continue
		}
		target := strings.TrimPrefix(importPath, modulePath)
		target = strings.TrimPrefix(target, "/")
		if target == "" {
			continue
		}
		edges = append(edges, moduleEdge{From: from, To: target})
	}
	return edges
}

var (
	jsImportFromPattern       = regexp.MustCompile(`(?m)^\s*import\s+.*?\s+from\s+['"]([^'"]+)['"]`)
	jsImportSideEffectPattern = regexp.MustCompile(`(?m)^\s*import\s+['"]([^'"]+)['"]`)
	jsRequirePattern          = regexp.MustCompile(`require\(\s*['"]([^'"]+)['"]\s*\)`)
	pyFromPattern             = regexp.MustCompile(`(?m)^\s*from\s+(\.+[A-Za-z0-9_\.]*)\s+import\s+`)
	phpNamespacePattern       = regexp.MustCompile(`(?m)^\s*namespace\s+([^;]+);`)
	phpUsePattern             = regexp.MustCompile(`(?m)^\s*use\s+([^;]+);`)
)

func parseJSImportEdges(root, path string) []moduleEdge {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	content := string(data)
	from := toProjectRelative(root, path)
	fromDir := filepath.Dir(path)
	edges := make([]moduleEdge, 0)

	for _, pattern := range []*regexp.Regexp{jsImportFromPattern, jsImportSideEffectPattern, jsRequirePattern} {
		for _, match := range pattern.FindAllStringSubmatch(content, -1) {
			if len(match) < 2 {
				continue
			}
			to := normalizeLocalJSImport(root, fromDir, match[1])
			if to == "" {
				continue
			}
			edges = append(edges, moduleEdge{From: from, To: to})
		}
	}
	return edges
}

func normalizeLocalJSImport(root, fromDir, spec string) string {
	if !strings.HasPrefix(spec, ".") {
		return ""
	}
	abs := filepath.Clean(filepath.Join(fromDir, spec))
	return toProjectRelative(root, abs)
}

func parsePythonImportEdges(root, path string) []moduleEdge {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	content := string(data)
	from := toProjectRelative(root, path)
	fromDir := filepath.Dir(path)
	edges := make([]moduleEdge, 0)

	for _, match := range pyFromPattern.FindAllStringSubmatch(content, -1) {
		if len(match) < 2 {
			continue
		}
		to := normalizeRelativePythonImport(root, fromDir, match[1])
		if to == "" {
			continue
		}
		edges = append(edges, moduleEdge{From: from, To: to})
	}
	return edges
}

func normalizeRelativePythonImport(root, fromDir, spec string) string {
	dots := 0
	for dots < len(spec) && spec[dots] == '.' {
		dots++
	}
	if dots == 0 {
		return ""
	}

	rest := strings.TrimPrefix(spec, strings.Repeat(".", dots))
	base := fromDir
	for i := 1; i < dots; i++ {
		base = filepath.Dir(base)
	}
	if rest == "" {
		return toProjectRelative(root, base)
	}
	restPath := strings.ReplaceAll(rest, ".", string(filepath.Separator))
	abs := filepath.Join(base, restPath)
	return toProjectRelative(root, abs)
}

func parsePHPAutoloadMappings(root string) []phpAutoloadMapping {
	data, err := os.ReadFile(filepath.Join(root, "composer.json"))
	if err != nil {
		return nil
	}

	var composer struct {
		Autoload struct {
			PSR4 map[string]string `json:"psr-4"`
		} `json:"autoload"`
		AutoloadDev struct {
			PSR4 map[string]string `json:"psr-4"`
		} `json:"autoload-dev"`
	}
	if err := json.Unmarshal(data, &composer); err != nil {
		return nil
	}

	mappings := make([]phpAutoloadMapping, 0)
	appendMappings := func(psr4 map[string]string) {
		for prefix, dir := range psr4 {
			prefix = strings.TrimSpace(prefix)
			dir = filepath.ToSlash(strings.TrimSpace(dir))
			dir = strings.Trim(dir, "/")
			if prefix == "" || dir == "" {
				continue
			}
			mappings = append(mappings, phpAutoloadMapping{
				Prefix: prefix,
				Dir:    dir,
			})
		}
	}

	appendMappings(composer.Autoload.PSR4)
	appendMappings(composer.AutoloadDev.PSR4)

	sort.Slice(mappings, func(i, j int) bool {
		return len(mappings[i].Prefix) > len(mappings[j].Prefix)
	})
	return mappings
}

func parsePHPImportEdges(root, path string, mappings []phpAutoloadMapping) []moduleEdge {
	if len(mappings) == 0 {
		return nil
	}

	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	content := string(data)

	currentNamespace := ""
	if m := phpNamespacePattern.FindStringSubmatch(content); len(m) == 2 {
		currentNamespace = strings.TrimSpace(m[1])
	}

	from := phpNamespaceToProjectPath(currentNamespace, mappings)
	if from == "" {
		from = toProjectRelative(root, path)
	}

	edges := make([]moduleEdge, 0)
	for _, match := range phpUsePattern.FindAllStringSubmatch(content, -1) {
		if len(match) != 2 {
			continue
		}
		for _, targetNamespace := range expandPHPUseTargets(match[1]) {
			to := phpNamespaceToProjectPath(targetNamespace, mappings)
			if to == "" {
				continue
			}
			edges = append(edges, moduleEdge{From: from, To: to})
		}
	}
	return edges
}

func expandPHPUseTargets(raw string) []string {
	raw = strings.TrimSpace(raw)
	raw = strings.TrimPrefix(raw, `\`)
	if raw == "" || strings.HasPrefix(raw, "function ") || strings.HasPrefix(raw, "const ") {
		return nil
	}

	if braceStart := strings.Index(raw, "{"); braceStart >= 0 && strings.HasSuffix(raw, "}") {
		prefix := strings.TrimSpace(raw[:braceStart])
		prefix = strings.TrimSuffix(prefix, `\`)
		inner := strings.TrimSuffix(raw[braceStart+1:], "}")
		items := strings.Split(inner, ",")
		out := make([]string, 0, len(items))
		for _, item := range items {
			item = stripPHPAlias(item)
			item = strings.TrimPrefix(strings.TrimSpace(item), `\`)
			if item == "" {
				continue
			}
			out = append(out, prefix+`\`+item)
		}
		return out
	}

	target := stripPHPAlias(raw)
	target = strings.TrimPrefix(strings.TrimSpace(target), `\`)
	if target == "" {
		return nil
	}
	return []string{target}
}

func stripPHPAlias(raw string) string {
	aliasSplit := regexp.MustCompile(`\s+as\s+`).Split(strings.TrimSpace(raw), 2)
	return strings.TrimSpace(aliasSplit[0])
}

func phpNamespaceToProjectPath(namespace string, mappings []phpAutoloadMapping) string {
	namespace = strings.TrimSpace(strings.TrimPrefix(namespace, `\`))
	if namespace == "" {
		return ""
	}

	for _, mapping := range mappings {
		if !strings.HasPrefix(namespace, mapping.Prefix) {
			continue
		}
		rest := strings.TrimPrefix(namespace, mapping.Prefix)
		rest = strings.ReplaceAll(rest, `\`, "/")
		rest = strings.Trim(rest, "/")
		if rest == "" {
			return mapping.Dir
		}
		return filepath.ToSlash(filepath.Join(mapping.Dir, rest))
	}
	return ""
}

func toProjectRelative(root, absPath string) string {
	rel, err := filepath.Rel(root, absPath)
	if err != nil {
		return ""
	}
	rel = filepath.ToSlash(rel)
	rel = strings.TrimPrefix(rel, "./")
	if rel == "." || strings.HasPrefix(rel, "../") {
		return ""
	}
	return rel
}
