package render

import (
	"bufio"
	"fmt"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"text/template"

	"github.com/oleksandrskoruk/docusnap/internal/model"
)

var templateSources = map[string]string{
	"README.generated.md": `# Project Documentation

Generated by DocuSnap.

## Overview
- Path: {{ .ProjectPath }}
- Scanned at: {{ .ScannedAt }}

## Languages
{{- if .Languages }}
{{- range .Languages }}
- {{ . }}
{{- end }}
{{- else }}
- n/a
{{- end }}

## Frameworks
{{- if .Frameworks }}
{{- range .Frameworks }}
- {{ . }}
{{- end }}
{{- else }}
- n/a
{{- end }}

## Artifacts
- [Dependencies](dependencies.md)
- [Dependency Graph](dependency-graph.md)
- [Module Graph](module-graph.md)
- [Endpoints](endpoints.md)
- [Architecture](architecture.md)
`,
	"dependencies.md": `# Dependencies

{{- if .DependencyManagers }}
{{- range .DependencyManagers }}
## {{ . }}
{{- $deps := index $.Dependencies . }}
{{- if $deps }}
| Name | Version |
|---|---|
{{- range $deps }}
| {{ .Name }} | {{ .Version }} |
{{- end }}
{{- else }}
No dependencies detected.
{{- end }}

{{- end }}
{{- else }}
No dependencies detected.
{{- end }}
`,
	"endpoints.md": `# API Endpoints

{{- if .Routes }}
| Method | Path | Controller |
|---|---|---|
{{- range .Routes }}
| {{ .Method }} | {{ .Path }} | {{ .Controller }} |
{{- end }}
{{- else }}
No endpoints detected for the current project.
{{- end }}
`,
	"dependency-graph.md": `# Dependency Graph

{{- if .DependencyGraphMermaid }}
{{ .DependencyGraphMermaid }}
{{- else }}
No dependencies detected.
{{- end }}
`,
	"module-graph.md": `# Module Graph

{{- if .ModuleGraphMermaid }}
{{ .ModuleGraphMermaid }}
{{- else }}
No module links detected.
{{- end }}
`,
	"architecture.md": `# Architecture

## Layer Diagram

~~~mermaid
graph TD
Controllers --> Services
Services --> Repositories
Repositories --> Database
~~~

## Technology View
{{- if .Frameworks }}
{{- range .Frameworks }}
- Framework: {{ . }}
{{- end }}
{{- else }}
- Framework: n/a
{{- end }}
{{- if .Infrastructure }}
{{- range .Infrastructure }}
- Infrastructure: {{ . }}
{{- end }}
{{- else }}
- Infrastructure: n/a
{{- end }}
`,
}

var templateNameByOutput = map[string]string{
	"README.generated.md": "readme.md.tmpl",
	"dependencies.md":     "dependencies.md.tmpl",
	"endpoints.md":        "endpoints.md.tmpl",
	"dependency-graph.md": "dependency-graph.md.tmpl",
	"module-graph.md":     "module-graph.md.tmpl",
	"architecture.md":     "architecture.md.tmpl",
}

type templateData struct {
	model.Snapshot
	DependencyManagers     []string
	DependencyGraphMermaid string
	ModuleGraphMermaid     string
}

// Generate writes the markdown documentation set to outDir.
func Generate(snap model.Snapshot, outDir string) ([]string, error) {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return nil, err
	}

	managers := make([]string, 0, len(snap.Dependencies))
	for manager := range snap.Dependencies {
		managers = append(managers, manager)
	}
	sort.Strings(managers)

	data := templateData{
		Snapshot:               snap,
		DependencyManagers:     managers,
		DependencyGraphMermaid: buildDependencyGraphMermaid(snap.Dependencies),
		ModuleGraphMermaid:     buildModuleGraphMermaid(snap.ProjectPath),
	}

	generated := make([]string, 0, len(templateSources))
	templateDir := filepath.Join(snap.ProjectPath, "templates")
	for name, src := range templateSources {
		path := filepath.Join(outDir, name)
		templateBody, err := resolveTemplateSource(templateDir, name, src)
		if err != nil {
			return nil, err
		}
		if err := renderFile(path, templateBody, data); err != nil {
			return nil, fmt.Errorf("render %s: %w", name, err)
		}
		generated = append(generated, path)
	}

	sort.Strings(generated)
	return generated, nil
}

func renderFile(path, src string, data templateData) error {
	tmpl, err := template.New(filepath.Base(path)).Parse(src)
	if err != nil {
		return err
	}

	var b strings.Builder
	if err := tmpl.Execute(&b, data); err != nil {
		return err
	}

	return os.WriteFile(path, []byte(strings.TrimSpace(b.String())+"\n"), 0o644)
}

func resolveTemplateSource(templateDir, outName, fallback string) (string, error) {
	templateName, ok := templateNameByOutput[outName]
	if !ok {
		return fallback, nil
	}

	customPath := filepath.Join(templateDir, templateName)
	data, err := os.ReadFile(customPath)
	if err != nil {
		if os.IsNotExist(err) {
			return fallback, nil
		}
		return "", fmt.Errorf("read template %s: %w", customPath, err)
	}

	body := strings.TrimSpace(string(data))
	if body == "" {
		return fallback, nil
	}

	return body, nil
}

func buildDependencyGraphMermaid(deps map[string][]model.Dependency) string {
	if len(deps) == 0 {
		return ""
	}

	managers := make([]string, 0, len(deps))
	for manager := range deps {
		managers = append(managers, manager)
	}
	sort.Strings(managers)

	var b strings.Builder
	b.WriteString("~~~mermaid\n")
	b.WriteString("graph LR\n")
	b.WriteString(`  P["Project"]` + "\n")

	for i, manager := range managers {
		managerID := fmt.Sprintf("PM%d", i+1)
		b.WriteString(fmt.Sprintf(`  %s["%s"]`+"\n", managerID, escapeMermaidLabel(manager)))
		b.WriteString(fmt.Sprintf("  P --> %s\n", managerID))

		for j, dep := range deps[manager] {
			depID := fmt.Sprintf("D%d_%d", i+1, j+1)
			b.WriteString(fmt.Sprintf(`  %s["%s"]`+"\n", depID, escapeMermaidLabel(dep.Name)))
			b.WriteString(fmt.Sprintf("  %s --> %s\n", managerID, depID))
		}
	}

	b.WriteString("~~~")
	return b.String()
}

func escapeMermaidLabel(v string) string {
	return strings.ReplaceAll(v, `"`, `'`)
}

type moduleEdge struct {
	From string
	To   string
}

func buildModuleGraphMermaid(root string) string {
	edges := collectModuleImportEdges(root)
	if len(edges) == 0 {
		return ""
	}

	nodeID := map[string]string{}
	nodes := make([]string, 0)
	nextID := 1
	for _, edge := range edges {
		if _, ok := nodeID[edge.From]; !ok {
			nodeID[edge.From] = fmt.Sprintf("M%d", nextID)
			nextID++
			nodes = append(nodes, edge.From)
		}
		if _, ok := nodeID[edge.To]; !ok {
			nodeID[edge.To] = fmt.Sprintf("M%d", nextID)
			nextID++
			nodes = append(nodes, edge.To)
		}
	}

	var b strings.Builder
	b.WriteString("~~~mermaid\n")
	b.WriteString("graph LR\n")
	for _, label := range nodes {
		b.WriteString(fmt.Sprintf(`  %s["%s"]`+"\n", nodeID[label], escapeMermaidLabel(label)))
	}
	for _, edge := range edges {
		b.WriteString(fmt.Sprintf("  %s --> %s\n", nodeID[edge.From], nodeID[edge.To]))
	}
	b.WriteString("~~~")
	return b.String()
}

func collectModuleImportEdges(root string) []moduleEdge {
	rootAbs, err := filepath.Abs(root)
	if err != nil {
		return nil
	}

	modulePath := parseGoModulePath(rootAbs)
	set := map[string]struct{}{}
	out := make([]moduleEdge, 0)

	_ = filepath.WalkDir(rootAbs, func(path string, d os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return nil
		}
		if d.IsDir() {
			base := d.Name()
			if base == ".git" || base == "node_modules" || base == "vendor" || strings.HasPrefix(base, ".") {
				if path != rootAbs {
					return filepath.SkipDir
				}
			}
			return nil
		}

		ext := strings.ToLower(filepath.Ext(path))
		var edges []moduleEdge
		switch ext {
		case ".go":
			edges = parseGoImportEdges(rootAbs, path, modulePath)
		case ".js", ".mjs", ".cjs", ".ts":
			edges = parseJSImportEdges(rootAbs, path)
		case ".py":
			edges = parsePythonImportEdges(rootAbs, path)
		default:
			return nil
		}

		for _, edge := range edges {
			if edge.From == "" || edge.To == "" || edge.From == edge.To {
				continue
			}
			key := edge.From + "->" + edge.To
			if _, ok := set[key]; ok {
				continue
			}
			set[key] = struct{}{}
			out = append(out, edge)
		}
		return nil
	})

	sort.Slice(out, func(i, j int) bool {
		if out[i].From == out[j].From {
			return out[i].To < out[j].To
		}
		return out[i].From < out[j].From
	})

	const maxEdges = 300
	if len(out) > maxEdges {
		return out[:maxEdges]
	}
	return out
}

func parseGoModulePath(root string) string {
	goModPath := filepath.Join(root, "go.mod")
	file, err := os.Open(goModPath)
	if err != nil {
		return ""
	}
	defer file.Close()

	s := bufio.NewScanner(file)
	for s.Scan() {
		line := strings.TrimSpace(s.Text())
		if strings.HasPrefix(line, "module ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "module "))
		}
	}
	return ""
}

func parseGoImportEdges(root, path, modulePath string) []moduleEdge {
	fileSet := token.NewFileSet()
	f, err := parser.ParseFile(fileSet, path, nil, parser.ImportsOnly)
	if err != nil {
		return nil
	}

	from := toProjectRelative(root, path)
	edges := make([]moduleEdge, 0, len(f.Imports))
	for _, imp := range f.Imports {
		importPath := strings.Trim(imp.Path.Value, `"`)
		if modulePath == "" || !strings.HasPrefix(importPath, modulePath) {
			continue
		}
		target := strings.TrimPrefix(importPath, modulePath)
		target = strings.TrimPrefix(target, "/")
		if target == "" {
			continue
		}
		edges = append(edges, moduleEdge{From: from, To: target})
	}
	return edges
}

var (
	jsImportFromPattern       = regexp.MustCompile(`(?m)^\s*import\s+.*?\s+from\s+['"]([^'"]+)['"]`)
	jsImportSideEffectPattern = regexp.MustCompile(`(?m)^\s*import\s+['"]([^'"]+)['"]`)
	jsRequirePattern          = regexp.MustCompile(`require\(\s*['"]([^'"]+)['"]\s*\)`)
	pyFromPattern             = regexp.MustCompile(`(?m)^\s*from\s+(\.+[A-Za-z0-9_\.]*)\s+import\s+`)
)

func parseJSImportEdges(root, path string) []moduleEdge {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	content := string(data)
	from := toProjectRelative(root, path)
	fromDir := filepath.Dir(path)
	edges := make([]moduleEdge, 0)

	for _, pattern := range []*regexp.Regexp{jsImportFromPattern, jsImportSideEffectPattern, jsRequirePattern} {
		for _, match := range pattern.FindAllStringSubmatch(content, -1) {
			if len(match) < 2 {
				continue
			}
			to := normalizeLocalJSImport(root, fromDir, match[1])
			if to == "" {
				continue
			}
			edges = append(edges, moduleEdge{From: from, To: to})
		}
	}
	return edges
}

func normalizeLocalJSImport(root, fromDir, spec string) string {
	if !strings.HasPrefix(spec, ".") {
		return ""
	}
	abs := filepath.Clean(filepath.Join(fromDir, spec))
	return toProjectRelative(root, abs)
}

func parsePythonImportEdges(root, path string) []moduleEdge {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	content := string(data)
	from := toProjectRelative(root, path)
	fromDir := filepath.Dir(path)
	edges := make([]moduleEdge, 0)

	for _, match := range pyFromPattern.FindAllStringSubmatch(content, -1) {
		if len(match) < 2 {
			continue
		}
		to := normalizeRelativePythonImport(root, fromDir, match[1])
		if to == "" {
			continue
		}
		edges = append(edges, moduleEdge{From: from, To: to})
	}
	return edges
}

func normalizeRelativePythonImport(root, fromDir, spec string) string {
	dots := 0
	for dots < len(spec) && spec[dots] == '.' {
		dots++
	}
	if dots == 0 {
		return ""
	}

	rest := strings.TrimPrefix(spec, strings.Repeat(".", dots))
	base := fromDir
	for i := 1; i < dots; i++ {
		base = filepath.Dir(base)
	}
	if rest == "" {
		return toProjectRelative(root, base)
	}
	restPath := strings.ReplaceAll(rest, ".", string(filepath.Separator))
	abs := filepath.Join(base, restPath)
	return toProjectRelative(root, abs)
}

func toProjectRelative(root, absPath string) string {
	rel, err := filepath.Rel(root, absPath)
	if err != nil {
		return ""
	}
	rel = filepath.ToSlash(rel)
	rel = strings.TrimPrefix(rel, "./")
	if rel == "." || strings.HasPrefix(rel, "../") {
		return ""
	}
	return rel
}
