package render

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"github.com/oleksandrskoruk/docusnap/internal/model"
)

var templateSources = map[string]string{
	"README.generated.md": `# Project Documentation

Generated by DocuSnap.

## Overview
- Path: {{ .ProjectPath }}
- Scanned at: {{ .ScannedAt }}

## Languages
{{- if .Languages }}
{{- range .Languages }}
- {{ . }}
{{- end }}
{{- else }}
- n/a
{{- end }}

## Frameworks
{{- if .Frameworks }}
{{- range .Frameworks }}
- {{ . }}
{{- end }}
{{- else }}
- n/a
{{- end }}

## Artifacts
- [Dependencies](dependencies.md)
- [Endpoints](endpoints.md)
- [Architecture](architecture.md)
`,
	"dependencies.md": `# Dependencies

{{- if .DependencyManagers }}
{{- range .DependencyManagers }}
## {{ . }}
{{- $deps := index $.Dependencies . }}
{{- if $deps }}
| Name | Version |
|---|---|
{{- range $deps }}
| {{ .Name }} | {{ .Version }} |
{{- end }}
{{- else }}
No dependencies detected.
{{- end }}

{{- end }}
{{- else }}
No dependencies detected.
{{- end }}
`,
	"endpoints.md": `# API Endpoints

{{- if .Routes }}
| Method | Path | Controller |
|---|---|---|
{{- range .Routes }}
| {{ .Method }} | {{ .Path }} | {{ .Controller }} |
{{- end }}
{{- else }}
No endpoints detected for the current project.
{{- end }}
`,
	"architecture.md": `# Architecture

## Layer Diagram

~~~mermaid
graph TD
Controllers --> Services
Services --> Repositories
Repositories --> Database
~~~

## Technology View
{{- if .Frameworks }}
{{- range .Frameworks }}
- Framework: {{ . }}
{{- end }}
{{- else }}
- Framework: n/a
{{- end }}
{{- if .Infrastructure }}
{{- range .Infrastructure }}
- Infrastructure: {{ . }}
{{- end }}
{{- else }}
- Infrastructure: n/a
{{- end }}
`,
}

var templateNameByOutput = map[string]string{
	"README.generated.md": "readme.md.tmpl",
	"dependencies.md":     "dependencies.md.tmpl",
	"endpoints.md":        "endpoints.md.tmpl",
	"architecture.md":     "architecture.md.tmpl",
}

type templateData struct {
	model.Snapshot
	DependencyManagers []string
}

// Generate writes the markdown documentation set to outDir.
func Generate(snap model.Snapshot, outDir string) ([]string, error) {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return nil, err
	}

	managers := make([]string, 0, len(snap.Dependencies))
	for manager := range snap.Dependencies {
		managers = append(managers, manager)
	}
	sort.Strings(managers)

	data := templateData{
		Snapshot:           snap,
		DependencyManagers: managers,
	}

	generated := make([]string, 0, len(templateSources))
	templateDir := filepath.Join(snap.ProjectPath, "templates")
	for name, src := range templateSources {
		path := filepath.Join(outDir, name)
		templateBody, err := resolveTemplateSource(templateDir, name, src)
		if err != nil {
			return nil, err
		}
		if err := renderFile(path, templateBody, data); err != nil {
			return nil, fmt.Errorf("render %s: %w", name, err)
		}
		generated = append(generated, path)
	}

	sort.Strings(generated)
	return generated, nil
}

func renderFile(path, src string, data templateData) error {
	tmpl, err := template.New(filepath.Base(path)).Parse(src)
	if err != nil {
		return err
	}

	var b strings.Builder
	if err := tmpl.Execute(&b, data); err != nil {
		return err
	}

	return os.WriteFile(path, []byte(strings.TrimSpace(b.String())+"\n"), 0o644)
}

func resolveTemplateSource(templateDir, outName, fallback string) (string, error) {
	templateName, ok := templateNameByOutput[outName]
	if !ok {
		return fallback, nil
	}

	customPath := filepath.Join(templateDir, templateName)
	data, err := os.ReadFile(customPath)
	if err != nil {
		if os.IsNotExist(err) {
			return fallback, nil
		}
		return "", fmt.Errorf("read template %s: %w", customPath, err)
	}

	body := strings.TrimSpace(string(data))
	if body == "" {
		return fallback, nil
	}

	return body, nil
}
